namespace EducationalPlatformITCube.Inspector.Web.Server.Pages.Classes
{
    public class DB
    {
        public List<RequestModel> RequestModels { get; set; } = new List<RequestModel>{
            new RequestModel
    {
        Id = 1,
        Email = "emilbarish@gmail.com",
        LastName = "Иванов",
        FirstName = "Иван",
        MiddleName = "Рюрикович",
        DateOfBirth = new DateTime(2009, 5, 20),
        Age = 14,
        SchoolNumber = 175,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петров",
        ParentFirstName = "Петр",
        ParentMiddleName = "Романович",
        ParentPhoneNumber = "+79393378504",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 2,
        Email = "test1@mail.com",
        LastName = "Смирнов",
        FirstName = "Иван",
        MiddleName = "Иванович",
        DateOfBirth = new DateTime(2008, 10, 5),
        Age = 13,
        SchoolNumber = 123,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Смирнова",
        ParentFirstName = "Мария",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79123456789",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 3,
        Email = "test2@mail.com",
        LastName = "Иванов",
        FirstName = "Алексей",
        MiddleName = "Андреевич",
        DateOfBirth = new DateTime(2010, 3, 15),
        Age = 12,
        SchoolNumber = 456,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Иванова",
        ParentFirstName = "Елена",
        ParentMiddleName = "Анатольевна",
        ParentPhoneNumber = "+79098765432",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 4,
        Email = "test3@mail.com",
        LastName = "Смирнова",
        FirstName = "Анна",
        MiddleName = "Петровна",
        DateOfBirth = new DateTime(2009, 8, 10),
        Age = 14,
        SchoolNumber = 789,
        Session = "Вторая",
        StudyDirection = "Python",
        ParentLastName = "Смирнов",
        ParentFirstName = "Петр",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79876543210",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 5,
        Email = "test4@mail.com",
        LastName = "Петров",
        FirstName = "Сергей",
        MiddleName = "Алексеевич",
        DateOfBirth = new DateTime(2011, 2, 25),
        Age = 11,
        SchoolNumber = 234,
        Session = "Первая",
        StudyDirection = "Java",
        ParentLastName = "Петрова",
        ParentFirstName = "Екатерина",
        ParentMiddleName = "Сергеевна",
        ParentPhoneNumber = "+79785634129",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 6,
        Email = "test5@mail.com",
        LastName = "Сидоров",
        FirstName = "Никита",
        MiddleName = "Дмитриевич",
        DateOfBirth = new DateTime(2010, 7, 12),
        Age = 12,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Сидорова",
        ParentFirstName = "Ольга",
        ParentMiddleName = "Дмитриевна",
        ParentPhoneNumber = "+79671234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 7,
        Email = "test6@mail.com",
        LastName = "Петров",
        FirstName = "Артем",
        MiddleName = "Игоревич",
        DateOfBirth = new DateTime(2009, 11, 8),
        Age = 13,
        SchoolNumber = 345,
        Session = "Вторая",
        StudyDirection = "SA",
        ParentLastName = "Петрова",
        ParentFirstName = "Ирина",
        ParentMiddleName = "Игоревна",
        ParentPhoneNumber = "+79991234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 8,
        Email = "test7@mail.com",
        LastName = "Смирнова",
        FirstName = "Дарья",
        MiddleName = "Андреевна",
        DateOfBirth = new DateTime(2010, 4, 18),
        Age = 12,
        SchoolNumber = 678,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Смирнов",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Андреевич",
        ParentPhoneNumber = "+79891234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 9,
        Email = "test8@mail.com",
        LastName = "Иванова",
        FirstName = "Анастасия",
        MiddleName = "Павловна",
        DateOfBirth = new DateTime(2009, 9, 30),
        Age = 14,
        SchoolNumber = 123,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванов",
        ParentFirstName = "Павел",
        ParentMiddleName = "Владимирович",
        ParentPhoneNumber = "+79781234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 10,
        Email = "test9@mail.com",
        LastName = "Сидоров",
        FirstName = "Алиса",
        MiddleName = "Сергеевна",
        DateOfBirth = new DateTime(2010, 6, 22),
        Age = 12,
        SchoolNumber = 456,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Сидорова",
        ParentFirstName = "Сергия",
        ParentMiddleName = "Игоревна",
        ParentPhoneNumber = "+79871234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 11,
        Email = "test10@mail.com",
        LastName = "Петров",
        FirstName = "Илья",
        MiddleName = "Михайлович",
        DateOfBirth = new DateTime(2009, 12, 12),
        Age = 13,
        SchoolNumber = 789,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Марина",
        ParentMiddleName = "Михайловна",
        ParentPhoneNumber = "+79811234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 12,
        Email = "test11@mail.com",
        LastName = "Смирнов",
        FirstName = "Максим",
        MiddleName = "Игоревич",
        DateOfBirth = new DateTime(2011, 1, 5),
        Age = 11,
        SchoolNumber = 234,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Смирнова",
        ParentFirstName = "Алена",
        ParentMiddleName = "Игоревна",
        ParentPhoneNumber = "+79891234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 13,
        Email = "test12@mail.com",
        LastName = "Иванова",
        FirstName = "Александра",
        MiddleName = "Алексеевна",
        DateOfBirth = new DateTime(2010, 8, 20),
        Age = 12,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Иванов",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79991234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 14,
        Email = "test13@mail.com",
        LastName = "Смирнова",
        FirstName = "Виктория",
        MiddleName = "Ивановна",
        DateOfBirth = new DateTime(2009, 10, 15),
        Age = 14,
        SchoolNumber = 345,
        Session = "Вторая",
        StudyDirection = "SA",
        ParentLastName = "Смирнов",
        ParentFirstName = "Иван",
        ParentMiddleName = "Иванович",
        ParentPhoneNumber = "+79671234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 15,
        Email = "test14@mail.com",
        LastName = "Петров",
        FirstName = "Матвей",
        MiddleName = "Сергеевич",
        DateOfBirth = new DateTime(2010, 5, 8),
        Age = 12,
        SchoolNumber = 678,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Светлана",
        ParentMiddleName = "Сергеевна",
        ParentPhoneNumber = "+79781234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 16,
        Email = "test15@mail.com",
        LastName = "Иванов",
        FirstName = "Арсений",
        MiddleName = "Александрович",
        DateOfBirth = new DateTime(2009, 7, 18),
        Age = 13,
        SchoolNumber = 123,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванова",
        ParentFirstName = "Анна",
        ParentMiddleName = "Александровна",
        ParentPhoneNumber = "+79871234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 17,
        Email = "test16@mail.com",
        LastName = "Сидоров",
        FirstName = "Валерия",
        MiddleName = "Николаевна",
        DateOfBirth = new DateTime(2010, 3, 22),
        Age = 12,
        SchoolNumber = 456,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Сидорова",
        ParentFirstName = "Татьяна",
        ParentMiddleName = "Игоревна",
        ParentPhoneNumber = "+79991234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 18,
        Email = "test17@mail.com",
        LastName = "Петров",
        FirstName = "Михаил",
        MiddleName = "Петрович",
        DateOfBirth = new DateTime(2009, 11, 5),
        Age = 13,
        SchoolNumber = 789,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Елена",
        ParentMiddleName = "Михайловна",
        ParentPhoneNumber = "+79891234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 19,
        Email = "test18@mail.com",
        LastName = "Смирнова",
        FirstName = "Ангелина",
        MiddleName = "Александровна",
        DateOfBirth = new DateTime(2010, 6, 30),
        Age = 12,
        SchoolNumber = 234,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Смирнов",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79781234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 20,
        Email = "test19@mail.com",
        LastName = "Иванова",
        FirstName = "Милана",
        MiddleName = "Сергеевна",
        DateOfBirth = new DateTime(2009, 8, 12),
        Age = 14,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Иванов",
        ParentFirstName = "Сергей",
        ParentMiddleName = "Игоревич",
        ParentPhoneNumber = "+79671234567",
        Status = "Ожидает обработки"
    },
    new RequestModel
    {
        Id = 21,
        Email = "test20@mail.com",
        LastName = "Смирнов",
        FirstName = "Иван",
        MiddleName = "Александрович",
        DateOfBirth = new DateTime(2009, 10, 15),
        Age = 13,
        SchoolNumber = 123,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Смирнова",
        ParentFirstName = "Ольга",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79101234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 22,
        Email = "test21@mail.com",
        LastName = "Иванова",
        FirstName = "Анастасия",
        MiddleName = "Игоревна",
        DateOfBirth = new DateTime(2010, 4, 28),
        Age = 12,
        SchoolNumber = 456,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванов",
        ParentFirstName = "Игорь",
        ParentMiddleName = "Петрович",
        ParentPhoneNumber = "+79211234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 23,
        Email = "test22@mail.com",
        LastName = "Петрова",
        FirstName = "Алина",
        MiddleName = "Алексеевна",
        DateOfBirth = new DateTime(2009, 11, 5),
        Age = 13,
        SchoolNumber = 789,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Петров",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79321234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 24,
        Email = "test23@mail.com",
        LastName = "Сидоров",
        FirstName = "Мария",
        MiddleName = "Петровна",
        DateOfBirth = new DateTime(2010, 8, 30),
        Age = 12,
        SchoolNumber = 234,
        Session = "Вторая",
        StudyDirection = "Python",
        ParentLastName = "Сидорова",
        ParentFirstName = "Елена",
        ParentMiddleName = "Сергеевна",
        ParentPhoneNumber = "+79451234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 25,
        Email = "test24@mail.com",
        LastName = "Иванов",
        FirstName = "Артем",
        MiddleName = "Владимирович",
        DateOfBirth = new DateTime(2009, 9, 12),
        Age = 14,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "Java",
        ParentLastName = "Иванова",
        ParentFirstName = "Вера",
        ParentMiddleName = "Владимировна",
        ParentPhoneNumber = "+79651234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 26,
        Email = "test25@mail.com",
        LastName = "Смирнова",
        FirstName = "Екатерина",
        MiddleName = "Андреевна",
        DateOfBirth = new DateTime(2010, 1, 8),
        Age = 12,
        SchoolNumber = 890,
        Session = "Вторая",
        StudyDirection = "R",
        ParentLastName = "Смирнов",
        ParentFirstName = "Андрей",
        ParentMiddleName = "Сергеевич",
        ParentPhoneNumber = "+79781234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 27,
        Email = "test26@mail.com",
        LastName = "Петров",
        FirstName = "Алиса",
        MiddleName = "Дмитриевна",
        DateOfBirth = new DateTime(2009, 7, 21),
        Age = 13,
        SchoolNumber = 123,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Марина",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79191234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 28,
        Email = "test27@mail.com",
        LastName = "Иванова",
        FirstName = "Виктория",
        MiddleName = "Игоревна",
        DateOfBirth = new DateTime(2010, 3, 4),
        Age = 12,
        SchoolNumber = 456,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванов",
        ParentFirstName = "Игорь",
        ParentMiddleName = "Петрович",
        ParentPhoneNumber = "+79221234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 29,
        Email = "test28@mail.com",
        LastName = "Петрова",
        FirstName = "Валерия",
        MiddleName = "Алексеевна",
        DateOfBirth = new DateTime(2009, 12, 18),
        Age = 13,
        SchoolNumber = 789,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Петров",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79331234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 30,
        Email = "test29@mail.com",
        LastName = "Сидоров",
        FirstName = "Анастасия",
        MiddleName = "Сергеевна",
        DateOfBirth = new DateTime(2010, 6, 26),
        Age = 12,
        SchoolNumber = 234,
        Session = "Вторая",
        StudyDirection = "Python",
        ParentLastName = "Сидорова",
        ParentFirstName = "Елена",
        ParentMiddleName = "Сергеевна",
        ParentPhoneNumber = "+79471234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 31,
        Email = "test30@mail.com",
        LastName = "Иванов",
        FirstName = "Андрей",
        MiddleName = "Михайлович",
        DateOfBirth = new DateTime(2009, 11, 2),
        Age = 14,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "Java",
        ParentLastName = "Иванова",
        ParentFirstName = "Мария",
        ParentMiddleName = "Михайловна",
        ParentPhoneNumber = "+79671234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 32,
        Email = "test31@mail.com",
        LastName = "Смирнова",
        FirstName = "Анастасия",
        MiddleName = "Петровна",
        DateOfBirth = new DateTime(2010, 2, 17),
        Age = 12,
        SchoolNumber = 890,
        Session = "Вторая",
        StudyDirection = "R",
        ParentLastName = "Смирнов",
        ParentFirstName = "Петр",
        ParentMiddleName = "Владимирович",
        ParentPhoneNumber = "+79791234567",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 33,
        Email = "test32@mail.com",
        LastName = "Петров",
        FirstName = "Мария",
        MiddleName = "Игоревна",
        DateOfBirth = new DateTime(2009, 8, 11),
        Age = 13,
        SchoolNumber = 123,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Анна",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79191234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 34,
        Email = "test33@mail.com",
        LastName = "Иванова",
        FirstName = "Елизавета",
        MiddleName = "Игоревна",
        DateOfBirth = new DateTime(2010, 5, 26),
        Age = 12,
        SchoolNumber = 456,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванов",
        ParentFirstName = "Игорь",
        ParentMiddleName = "Петрович",
        ParentPhoneNumber = "+79221234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 35,
        Email = "test34@mail.com",
        LastName = "Петрова",
        FirstName = "Дарья",
        MiddleName = "Алексеевна",
        DateOfBirth = new DateTime(2009, 10, 3),
        Age = 13,
        SchoolNumber = 789,
        Session = "Первая",
        StudyDirection = "R",
        ParentLastName = "Петров",
        ParentFirstName = "Алексей",
        ParentMiddleName = "Александрович",
        ParentPhoneNumber = "+79331234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 36,
        Email = "test35@mail.com",
        LastName = "Сидоров",
        FirstName = "Ирина",
        MiddleName = "Сергеевна",
        DateOfBirth = new DateTime(2010, 1, 20),
        Age = 12,
        SchoolNumber = 234,
        Session = "Вторая",
        StudyDirection = "Python",
        ParentLastName = "Сидорова",
        ParentFirstName = "Елена",
        ParentMiddleName = "Сергеевна",
        ParentPhoneNumber = "+79471234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 37,
        Email = "test36@mail.com",
        LastName = "Иванов",
        FirstName = "Александр",
        MiddleName = "Иванович",
        DateOfBirth = new DateTime(2009, 9, 25),
        Age = 14,
        SchoolNumber = 567,
        Session = "Первая",
        StudyDirection = "Java",
        ParentLastName = "Иванова",
        ParentFirstName = "Ольга",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79671234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 38,
        Email = "test37@mail.com",
        LastName = "Смирнова",
        FirstName = "Марина",
        MiddleName = "Андреевна",
        DateOfBirth = new DateTime(2010, 4, 8),
        Age = 12,
        SchoolNumber = 890,
        Session = "Вторая",
        StudyDirection = "R",
        ParentLastName = "Смирнов",
        ParentFirstName = "Андрей",
        ParentMiddleName = "Сергеевич",
        ParentPhoneNumber = "+79791234568",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 39,
        Email = "test38@mail.com",
        LastName = "Петров",
        FirstName = "Мария",
        MiddleName = "Ивановна",
        DateOfBirth = new DateTime(2009, 7, 13),
        Age = 13,
        SchoolNumber = 123,
        Session = "Первая",
        StudyDirection = "Python",
        ParentLastName = "Петрова",
        ParentFirstName = "Марина",
        ParentMiddleName = "Ивановна",
        ParentPhoneNumber = "+79191234569",
        Status = "Принят"
    },
    new RequestModel
    {
        Id = 40,
        Email = "test39@mail.com",
        LastName = "Иванова",
        FirstName = "Евгения",
        MiddleName = "Игоревна",
        DateOfBirth = new DateTime(2010, 3, 16),
        Age = 12,
        SchoolNumber = 456,
        Session = "Вторая",
        StudyDirection = "Java",
        ParentLastName = "Иванов",
        ParentFirstName = "Игорь",
        ParentMiddleName = "Петрович",
        ParentPhoneNumber = "+79221234569",
        Status = "Принят"
    }

        };

    }
}
